import { defineConfig } from 'vitepress'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  lang: 'ko-KR',
  title: 'algo-wiki',
  description: 'A VitePress Site',
  base:'/algo-wiki/',
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: '홈', link: '/' },
      { text: '이론', link: '/theory' },
      { text: '문제풀이', link: '/problems' },
    ],

    sidebar: {
      theory: [
        {
          text: '자료구조',
          base: '/theory/data-structure/',
          items: [
            { text: '연결 리스트 (Linked List)', link: 'linked-list/' },
            { text: '스택 (Stack)', link: 'stack/' },
            { text: '큐 (Queue)', link: 'queue/' },
          ],
        },
        {
          text: '알고리즘',
          base: '/theory/algorithm/',
          items: [
            { text: '너비 우선 탐색 (BFS)', link: 'bfs/' },
            { text: '깊이 우선 탐색 (DFS)', link: 'dfs/' },
            { text: '이진 탐색 (Binary Search)', link: 'binary-search/' },
            { text: '조합 (Combination)', link: 'combination/' },
            { text: '순열 (Permutation)', link: 'permutation/' },
            { text: '크루스칼 (Kruskal)', link: 'kruskal/' },
            { text: '프림 (Prim)', link: 'prim/' },
            { text: '최소 신장 트리 (MST)', link: 'mst/' },
            { text: '소수 (Prime Number)', link: 'prime-number/' },
            { text: '슬라이딩 윈도우 (Sliding Window)', link: 'sliding-window/' },
            { text: '유니온 파인드 (Union Find)', link: 'union-find/' },
          ],
        },
      ],
      problems: [
        {
          text: 'leetcode',
          collapsed: true,
          base: '/problems/leetcode/',
          items: [
            { text: '1 - Two Sum', link: 'p1' },
            { text: '2 - Add Two Numbers', link: 'p2' },
            { text: '3 - Longest Substring Without Repeating Characters', link: 'p3' },
            { text: '4 - Median of Two Sorted Arrays', link: 'p4' },
            { text: '5 - Longest Palindromic Substring', link: 'p5' },
            { text: '6 - Zigzag Conversion', link: 'p6' },
            { text: '7 - Reverse Integer', link: 'p7' },
            { text: '8 - String to Integer (atoi)', link: 'p8' },
            { text: '9 - Palindrome Number', link: 'p9' },
            { text: '10 - Regular Expression Matching', link: 'p10' },
            { text: '11 - Container With Most Water', link: 'p11' },
            { text: '12 - Integer to Roman', link: 'p12' },
            { text: '13 - Roman to Integer', link: 'p13' },
            { text: '14 - Longest Common Prefix', link: 'p14' },
            { text: '15 - 3Sum', link: 'p15' },
            { text: '16 - 3Sum Closest', link: 'p16' },
            { text: '17 - Letter Combinations of a Phone Number', link: 'p17' },
            { text: '18 - 4Sum', link: 'p18' },
            { text: '19 - Remove Nth Node From End of List', link: 'p19' },
            { text: '20 - Valid Parentheses', link: 'p20' },
            { text: '21 - Merge Two Sorted Lists', link: 'p21' },
            { text: '22 - Generate Parentheses', link: 'p22' },
            { text: '23 - Merge k Sorted Lists', link: 'p23' },
            { text: '24 - Swap Nodes in Pairs', link: 'p24' },
            { text: '25 - Reverse Nodes in k-Group', link: 'p25' },
            { text: '26 - Remove Duplicates from Sorted Array', link: 'p26' },
            { text: '27 - Remove Element', link: 'p27' },
            { text: '28 - Find the Index of the First Occurrence in a String', link: 'p28' },
            { text: '29 - Divide Two Integers', link: 'p29' },
            { text: '30 - Substring with Concatenation of All Words', link: 'p30' },
            { text: '31 - Next Permutation', link: 'p31' },
            { text: '32 - Longest Valid Parentheses', link: 'p32' },
            { text: '33 - Search in Rotated Sorted Array', link: 'p33' },
            { text: '34 - Find First and Last Position of Element in Sorted Array', link: 'p34' },
            { text: '35 - Search Insert Position', link: 'p35' },
            { text: '36 - Valid Sudoku', link: 'p36' },
            { text: '37 - Sudoku Solver', link: 'p37' },
            { text: '38 - Count and Say', link: 'p38' },
            { text: '39 - Combination Sum', link: 'p39' },
            { text: '40 - Combination Sum II', link: 'p40' },
            { text: '41 - First Missing Positive', link: 'p41' },
            { text: '45. Jump Game II (LeetCode)', link: '45. Jump Game II (LeetCode)' },
            { text: '55 - Jump Game', link: 'p55' },
            { text: '79 - Word Search', link: 'p79' },
            { text: '80 - Remove Duplicates from Sorted Array II', link: 'p80' },
            { text: '88 - Merge Sorted Array', link: 'p88' },
            { text: '121 - Best Time to Buy and Sell Stock', link: 'p121' },
            { text: '122 - Best Time to Buy and Sell Stock II', link: 'p122' },
            { text: '131 - Palindrome Partitioning', link: 'p131' },
            { text: '1544 - Make The String Great', link: 'p1544' },
            { text: '169 - Majority Element', link: 'p169' },
            { text: '189 - Rotate Array', link: 'p189' },
            { text: '263 - Ugly Number', link: 'p263' },
            { text: '268 - Missing Number', link: 'p268' },
            { text: '274. H-Index (LeetCode)', link: '274. H-Index (LeetCode)' },
            { text: '278 - First Bad Version', link: 'p278' },
            { text: '704 - Binary Search', link: 'p704' },
          ],
        },
        {
          text: 'codility',
          collapsed: true,
          base: '/problems/codility/',
          items: [
            { text: '1 - BinaryGap', link: 'BinaryGap' },
            { text: '2 - CountDiv', link: 'CountDiv' },
            { text: '3 - CyclicRotation', link: 'CyclicRotation' },
            { text: '4 - FrogJump', link: 'FrogJump' },
            { text: '5 - FrogRiverOne', link: 'FrogRiverOne' },
            { text: '6 - MaxCounter', link: 'MaxCounter' },
            { text: '7 - MissingInteger', link: 'MissingInteger' },
            { text: '8 - OddOccurrencesInArray', link: 'OddOccurrencesInArray' },
            { text: '9 - PassingCar', link: 'PassingCar' },
            { text: '10 - PermCheck', link: 'PermCheck' },
            { text: '11 - PermMissingElem', link: 'PermMissingElem' },
            { text: '12 - TapeEquilibrium', link: 'TapeEquilibrium' },
          ],
        },
        {
          text: '백준',
          collapsed: true,
          base: '/problems/baekjoon/',
          items: [],
        },
        {
          text: '프로그래머스',
          collapsed: true,
          base: '/problems/programmers/',
          items: [],
        },
        {
          text: 'Problem Folder (Custom)',
          collapsed: true,
          base: '/problems/custom/',
          items: [],
        },
      ],
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/253eosam/algo-wiki/' }],
  },
})
